# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  issue_comment:
    types:
    - created
    branches:
    - "**"

name: Verify
jobs:
  verify:
    name: Verify
#    if: ${{ github.event.head_commit.message == 'CI' }}
    if: ${{ (github.event.issue.pull_request != null) && github.event.comment.body == 'CI' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        nodejs:
        - 18
      fail-fast: false
    steps:
    - name: github
      run: echo '${{ toJSON(github) }}'
