# https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  issue_comment:
    types:
    - created
    branches:
    - "**"

name: Verify
jobs:
  verify:
    name: Verify
    if: ${{ (github.event_name == 'issue_comment') && (github.event.issue.pull_request != null) && (github.event.comment.body == '/ci') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v3
    - id: get-sha
      name: get SHA
      uses: ./.github/actions/get-sha
    - name: status to pending
      uses: ./.github/actions/status
      with:
        sha: ${{ steps.get-sha.outputs.sha }}
        state: pending
        token: ${{ secrets.GH_TOKEN }}

    # CI
    - name: github
      run: echo '${{ toJSON(github) }}'

    # update status
    - name: status to success
      uses: ./.github/actions/status
      with:
        sha: ${{ steps.get-sha.outputs.sha }}
        state: success
        token: ${{ secrets.GH_TOKEN }}
      if: ${{ success() }}
    - name: status to error
      uses: ./.github/actions/status
      with:
        sha: ${{ steps.get-sha.outputs.sha }}
        state: error
        token: ${{ secrets.GH_TOKEN }}
      if: ${{ failure() }}