# https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  issue_comment:
    types:
    - created
    branches:
    - "**"

name: Verify
jobs:
  verify:
    name: Verify
    if: ${{ (github.event_name == 'issue_comment') && (github.event.issue.pull_request != null) && (github.event.comment.body == '/ci') }}
#    if: ${{ contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/ci') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        nodejs:
        - 18
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v3
    - name: status to pending
      uses: ./.github/actions/status
      with:
        state: pending
    - name: github
      run: echo '${{ toJSON(github) }}'
    - name: status to success
      uses: ./.github/actions/status
      with:
        state: success
      if: ${{ success() }}
    - name: status to error
      uses: ./.github/actions/status
      with:
        state: error
      if: ${{ failure() }}