# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://buildersbox.corp-sansan.com/entry/2021/02/05/110000
# https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28

on:
  issue_comment:
    types:
    - created
    branches:
    - "**"

name: Verify
jobs:
  verify:
    name: Verify
    if: ${{ (github.event.issue.pull_request != null) && (github.event.comment.body == '/ci') }}
#    if: ${{ (github.event_name == 'issue_comment') && contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/ci') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        nodejs:
        - 18
      fail-fast: false
    steps:
    - name: github
      run: echo '${{ toJSON(github) }}'
    - name: Get branch name and sha
      id: get-sha
      run: |
        PR=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.issue.pull_request.url }})
        echo "sha=$(echo $PR | jq -r '.head.sha')" >> ${{ github.output }}
    - name: status
      run: >-
        curl
        -X POST
        -H "Accept: application/vnd.github+json"
        -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}"
        -H "X-GitHub-Api-Version: 2022-11-28"
        https://api.github.com/repos/${{ github.repository }}/statuses/${{ steps.get-sha.outputs.sha }}
        -d '{"state":"success","description":":+1:","context":"${{ github.workflow }}"}'