# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  pull_request_review:
    types:
    - "submitted"
    branches:
    - "**"
#  issue_comment:
#    types:
#    - created
#    branches:
#    - "**"

name: Verify
jobs:
  verify:
    name: Verify
#    if: ${{ github.event.head_commit.message == 'CI' }}
#    if: ${{ (github.event.issue.pull_request != null) && (github.event.comment.body == 'CI') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        nodejs:
        - 18
      fail-fast: false
    steps:
    - name: github
      run: echo '${{ toJSON(github) }}'
#    - name: status
#      run: >-
#        curl
#        -X POST
#        -H "Accept: application/vnd.github+json"
#        -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}"
#        -H "X-GitHub-Api-Version: 2022-11-28"
#        https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
#        -d '{"state":"success","description":"CI OK","context":"${{ github.workflow }}"}'
